#!/bin/sh

set -eu

SOURCE="sources/ai.list"
OUTPUT_DIR="output"

OUTPUT_YAML="$OUTPUT_DIR/AI.yaml"
OUTPUT_LIST="$OUTPUT_DIR/AI.list"
OUTPUT_MRS="$OUTPUT_DIR/AI.mrs"

echo "========================================"
echo "Crossing AI Rule Builder"
echo "========================================"

mkdir -p "$OUTPUT_DIR"

# ============================================================
# 检查源文件
# ============================================================

if [ ! -f "$SOURCE" ]; then
    echo "错误：找不到 $SOURCE"
    exit 1
fi

# ============================================================
# 清理旧数据
# ============================================================

TMP_RAW=$(mktemp)
TMP_IDN=$(mktemp)
TMP_SORTED=$(mktemp)

cleanup() {
    rm -f "$TMP_RAW" "$TMP_IDN" "$TMP_SORTED"
}

trap cleanup EXIT

# ============================================================
# 读取域名
# ============================================================

grep -v '^[[:space:]]*$' "$SOURCE" \
    | grep -v '^[[:space:]]*#' \
    | sed 's/[[:space:]]*#.*$//' \
    | sed 's/^[[:space:]]*//' \
    | sed 's/[[:space:]]*$//' \
    | sed 's/^DOMAIN-SUFFIX,//' \
    > "$TMP_RAW"

RAW_COUNT=$(grep -c . "$TMP_RAW" || true)

echo "原始域名：$RAW_COUNT"

# ============================================================
# IDN → Punycode
# ============================================================

python3 - "$TMP_RAW" "$TMP_IDN" <<'PY'
import sys

src = sys.argv[1]
dst = sys.argv[2]

with open(src, "r", encoding="utf-8") as f, \
     open(dst, "w", encoding="utf-8") as out:

    for line in f:
        domain = line.strip().lower()

        if not domain:
            continue

        try:
            domain = domain.encode("idna").decode("ascii")
        except Exception:
            pass

        domain = domain.rstrip(".")

        if domain:
            out.write(domain + "\n")
PY

# ============================================================
# 去重 + 排序
# ============================================================

sort -u "$TMP_IDN" > "$TMP_SORTED"

DOMAIN_COUNT=$(grep -c . "$TMP_SORTED" || true)

echo "去重后域名：$DOMAIN_COUNT"

# ============================================================
# 核心域名检查
# ============================================================

echo
echo "检查核心 AI 域名..."

REQUIRED_DOMAINS="
openai.com
chatgpt.com
api.openai.com
claude.ai
gemini.google.com
grok.com
copilot.microsoft.com
deepseek.com
perplexity.ai
"

for domain in $REQUIRED_DOMAINS; do
    if grep -Fxq "$domain" "$TMP_SORTED"; then
        echo "  ✓ $domain"
    else
        echo "  ✗ $domain"
        echo
        echo "错误：核心 AI 域名缺失"
        exit 1
    fi
done

# ============================================================
# 数量检查
# ============================================================

MIN_COUNT=20

if [ "$DOMAIN_COUNT" -lt "$MIN_COUNT" ]; then
    echo
    echo "错误：AI 规则数量异常"
    echo "当前：$DOMAIN_COUNT"
    echo "最低：$MIN_COUNT"
    exit 1
fi

# ============================================================
# SHA256
# ============================================================

SOURCE_SHA256=$(sha256sum "$SOURCE" | awk '{print $1}')

UPDATED=$(TZ="Asia/Shanghai" date +"%Y-%m-%d %H:%M:%S CST")

# ============================================================
# 生成 AI.yaml
# ============================================================

{
    echo "# NAME: AI"
    echo "# AUTHOR: hostzs"
    echo "# REPO: https://github.com/hostzs/crossing"
    echo "# UPDATED: $UPDATED"
    echo "# SOURCE-SHA256: $SOURCE_SHA256"
    echo "# COUNT: $DOMAIN_COUNT"
    echo "#"
    echo "# Generated by Crossing AI Rule Builder"
    echo

    while IFS= read -r domain
    do
        echo "  - $domain"
    done < "$TMP_SORTED"

} > "$OUTPUT_YAML"

# ============================================================
# 生成 AI.list
# ============================================================

{
    echo "# NAME: AI"
    echo "# AUTHOR: hostzs"
    echo "# REPO: https://github.com/hostzs/crossing"
    echo "# UPDATED: $UPDATED"
    echo "# SOURCE-SHA256: $SOURCE_SHA256"
    echo "# COUNT: $DOMAIN_COUNT"
    echo "#"

    while IFS= read -r domain
    do
        echo "$domain"
    done < "$TMP_SORTED"

} > "$OUTPUT_LIST"

# ============================================================
# 生成 MRS
# ============================================================

echo
echo "生成 AI.mrs..."

mihomo convert-ruleset domain text \
    "$OUTPUT_LIST" \
    "$OUTPUT_MRS"

# ============================================================
# 最终检查
# ============================================================

if [ ! -s "$OUTPUT_MRS" ]; then
    echo "错误：AI.mrs 生成失败"
    exit 1
fi

echo
echo "========================================"
echo "AI 规则生成完成"
echo "========================================"
echo
echo "域名数量：$DOMAIN_COUNT"
echo "YAML：$OUTPUT_YAML"
echo "LIST：$OUTPUT_LIST"
echo "MRS：$OUTPUT_MRS"
