#!/bin/sh

set -eu

SOURCE="sources/manual-proxy.list"
OUTPUT_DIR="output"

OUTPUT_YAML="$OUTPUT_DIR/proxy.yaml"
OUTPUT_LIST="$OUTPUT_DIR/proxy.list"
OUTPUT_MRS="$OUTPUT_DIR/proxy.mrs"

echo "========================================"
echo "Crossing Rule Builder"
echo "========================================"

echo "原始数据：$SOURCE"
echo "输出 YAML：$OUTPUT_YAML"
echo "输出 TEXT：$OUTPUT_LIST"
echo "输出 MRS：$OUTPUT_MRS"
echo

mkdir -p "$OUTPUT_DIR"

# ============================================================
# 保存旧输出，用于判断本次生成是否真的发生变化
# ============================================================

OLD_YAML=$(mktemp)
OLD_LIST=$(mktemp)
OLD_MRS=$(mktemp)

cleanup() {
    rm -f "$OLD_YAML" "$OLD_LIST" "$OLD_MRS"
}

trap cleanup EXIT

[ -f "$OUTPUT_YAML" ] && cp "$OUTPUT_YAML" "$OLD_YAML"
[ -f "$OUTPUT_LIST" ] && cp "$OUTPUT_LIST" "$OLD_LIST"
[ -f "$OUTPUT_MRS" ] && cp "$OUTPUT_MRS" "$OLD_MRS"

# ============================================================
# 读取域名
# ============================================================

TMP_RAW=$(mktemp)

grep -v '^[[:space:]]*$' "$SOURCE" \
    | grep -v '^[[:space:]]*#' \
    | sed 's/[[:space:]]*#.*$//' \
    | sed 's/^[[:space:]]*//' \
    | sed 's/[[:space:]]*$//' \
    > "$TMP_RAW"

# 兼容 DOMAIN-SUFFIX,example.com 写法
sed -i 's/^DOMAIN-SUFFIX,//' "$TMP_RAW"

RAW_COUNT=$(grep -c . "$TMP_RAW" || true)

echo "读取域名：$RAW_COUNT"

# ============================================================
# IDN 转 Punycode
# ============================================================

TMP_IDN=$(mktemp)

python3 - "$TMP_RAW" "$TMP_IDN" <<'PY'
import sys

src = sys.argv[1]
dst = sys.argv[2]

count = 0

with open(src, "r", encoding="utf-8") as f, \
     open(dst, "w", encoding="utf-8") as out:

    for line in f:
        domain = line.strip().lower()

        if not domain:
            continue

        try:
            domain = domain.encode("idna").decode("ascii")
        except Exception:
            pass

        domain = domain.rstrip(".")

        if domain:
            out.write(domain + "\n")
            count += 1

print(f"IDN 转换后：{count}")
PY

# ============================================================
# 去重 + 排序
# ============================================================

TMP_SORTED=$(mktemp)

sort -u "$TMP_IDN" > "$TMP_SORTED"

DOMAIN_COUNT=$(grep -c . "$TMP_SORTED" || true)

echo "去重后：$DOMAIN_COUNT"
echo

# ============================================================
# SOURCE SHA256
# ============================================================

SOURCE_SHA256=$(sha256sum "$SOURCE" | awk '{print $1}')

# ============================================================
# 更新时间
# ============================================================

UPDATED=$(date -u +"%Y-%m-%d %H:%M:%S UTC")

# ============================================================
# 生成 proxy.yaml
# ============================================================

{
    echo "# NAME: proxy"
    echo "# AUTHOR: edward"
    echo "# REPO: https://github.com/hostzs/crossing"
    echo "# UPDATED: $UPDATED"
    echo "# SOURCE-SHA256: $SOURCE_SHA256"
    echo "# COUNT: $DOMAIN_COUNT"
    echo "#"
    echo "# Generated by Crossing Rule Builder"
    echo

    while IFS= read -r domain
    do
        echo "  - $domain"
    done < "$TMP_SORTED"

} > "$OUTPUT_YAML"

# ============================================================
# 生成 proxy.list
# ============================================================

{
    echo "# NAME: proxy"
    echo "# AUTHOR: edward"
    echo "# REPO: https://github.com/hostzs/crossing"
    echo "# UPDATED: $UPDATED"
    echo "# SOURCE-SHA256: $SOURCE_SHA256"
    echo "# COUNT: $DOMAIN_COUNT"
    echo "#"

    while IFS= read -r domain
    do
        echo "$domain"
    done < "$TMP_SORTED"

} > "$OUTPUT_LIST"

echo "YAML 和 TEXT 生成完成"
echo

# ============================================================
# 生成 MRS
# ============================================================

echo "开始生成 MRS..."
echo

mihomo convert-ruleset domain text \
    "$OUTPUT_LIST" \
    "$OUTPUT_MRS"

echo

# ============================================================
# 判断实际输出是否变化
# ============================================================

YAML_CHANGED=0
LIST_CHANGED=0
MRS_CHANGED=0

if [ ! -f "$OLD_YAML" ] || ! cmp -s "$OUTPUT_YAML" "$OLD_YAML"; then
    YAML_CHANGED=1
fi

if [ ! -f "$OLD_LIST" ] || ! cmp -s "$OUTPUT_LIST" "$OLD_LIST"; then
    LIST_CHANGED=1
fi

if [ ! -f "$OLD_MRS" ] || ! cmp -s "$OUTPUT_MRS" "$OLD_MRS"; then
    MRS_CHANGED=1
fi

# ============================================================
# 如果只有 UPDATED 变化，则恢复旧文件
# ============================================================

if [ "$YAML_CHANGED" -eq 1 ] || \
   [ "$LIST_CHANGED" -eq 1 ] || \
   [ "$MRS_CHANGED" -eq 1 ]; then

    echo "检测到输出内容变化："

    if [ "$YAML_CHANGED" -eq 1 ]; then
        echo "  proxy.yaml：变化"
    else
        echo "  proxy.yaml：无变化"
    fi

    if [ "$LIST_CHANGED" -eq 1 ]; then
        echo "  proxy.list：变化"
    else
        echo "  proxy.list：无变化"
    fi

    if [ "$MRS_CHANGED" -eq 1 ]; then
        echo "  proxy.mrs：变化"
    else
        echo "  proxy.mrs：无变化"
    fi

else

    echo "输出内容没有变化"
    echo "恢复旧文件，避免因为 UPDATED 时间产生无意义提交"

    if [ -f "$OLD_YAML" ]; then
        cp "$OLD_YAML" "$OUTPUT_YAML"
    else
        rm -f "$OUTPUT_YAML"
    fi

    if [ -f "$OLD_LIST" ]; then
        cp "$OLD_LIST" "$OUTPUT_LIST"
    else
        rm -f "$OUTPUT_LIST"
    fi

    if [ -f "$OLD_MRS" ]; then
        cp "$OLD_MRS" "$OUTPUT_MRS"
    else
        rm -f "$OUTPUT_MRS"
    fi

fi

# ============================================================
# 清理临时文件
# ============================================================

rm -f "$TMP_RAW" "$TMP_IDN" "$TMP_SORTED"

echo
echo "生成完成："
echo "  域名数量：$DOMAIN_COUNT"
echo "  SHA256：$SOURCE_SHA256"
echo "  YAML：$OUTPUT_YAML"
echo "  TEXT：$OUTPUT_LIST"
echo "  MRS：$OUTPUT_MRS"
