#!/bin/sh

set -eu

# ========================================
# AI Rules Builder
# ========================================

BASE_DIR="$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)"

SOURCE_DIR="$BASE_DIR/sources/ai"
OUTPUT_DIR="$BASE_DIR/output"

CUSTOM="$SOURCE_DIR/custom.list"

OUTPUT_LIST="$OUTPUT_DIR/AI.list"
OUTPUT_YAML="$OUTPUT_DIR/AI.yaml"
OUTPUT_MRS="$OUTPUT_DIR/AI.mrs"

TMP_DIR="$(mktemp -d)"

trap 'rm -rf "$TMP_DIR"' EXIT

mkdir -p "$SOURCE_DIR"
mkdir -p "$OUTPUT_DIR"

echo "========================================"
echo "AI Rules Builder"
echo "========================================"
echo

# ========================================
# 1. 第三方规则源
# ========================================

SOURCES="
OpenAI|https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/OpenAI/OpenAI.list
Claude|https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Claude/Claude.list
Gemini|https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Gemini/Gemini.list
Copilot|https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Copilot/Copilot.list
"

# ========================================
# 2. 下载第三方规则
# ========================================

ALL_RULES="$TMP_DIR/all.rules"

: > "$ALL_RULES"

echo "下载 AI 第三方规则："
echo

printf '%s\n' "$SOURCES" |
while IFS='|' read -r NAME URL
do
    [ -n "$NAME" ] || continue

    FILE="$TMP_DIR/${NAME}.list"

    echo "[$NAME]"
    echo "$URL"

    if curl -fsSL \
        --retry 3 \
        --retry-delay 2 \
        --connect-timeout 15 \
        --max-time 120 \
        "$URL" \
        -o "$FILE"
    then
        echo "下载成功"

        # --------------------------------
        # 只提取 DOMAIN / DOMAIN-SUFFIX
        # --------------------------------

        awk -F',' '
            /^[[:space:]]*#/ { next }

            /^[[:space:]]*DOMAIN,/ {
                print $2
                next
            }

            /^[[:space:]]*DOMAIN-SUFFIX,/ {
                print $2
                next
            }
        ' "$FILE" >> "$ALL_RULES"

    else
        echo "警告：$NAME 下载失败"
        echo "继续使用其他来源"
    fi

    echo
done

# ========================================
# 3. 加入本地核心规则
# ========================================

if [ -f "$CUSTOM" ]; then
    echo "加入本地核心规则：$CUSTOM"

    cat "$CUSTOM" >> "$ALL_RULES"
else
    echo "错误：找不到 $CUSTOM"
    exit 1
fi

# ========================================
# 4. 标准化域名
# ========================================

NORMALIZED="$TMP_DIR/normalized.list"

awk '
{
    gsub(/\r/, "")
    gsub(/^[ \t]+|[ \t]+$/, "")

    if ($0 == "") next
    if ($0 ~ /^#/) next

    # 去掉可能存在的 DOMAIN-SUFFIX / DOMAIN 前缀
    sub(/^DOMAIN-SUFFIX,/, "")
    sub(/^DOMAIN,/, "")

    # 去掉尾部句点
    sub(/\.$/, "")

    print tolower($0)
}
' "$ALL_RULES" |
grep -E '^[A-Za-z0-9][A-Za-z0-9._-]*$' |
sort -u > "$NORMALIZED"

# ========================================
# 5. 基础检查
# ========================================

COUNT="$(wc -l < "$NORMALIZED" | tr -d ' ')"

echo
echo "========================================"
echo "规则统计"
echo "========================================"
echo "AI 域名数量：$COUNT"
echo

# 防止第三方规则全部失效导致生成空规则
MIN_COUNT=20

if [ "$COUNT" -lt "$MIN_COUNT" ]; then
    echo "错误：AI 规则数量异常"
    echo "当前：$COUNT"
    echo "最低要求：$MIN_COUNT"
    exit 1
fi

# ========================================
# 6. 核心域名检查
# ========================================

echo "检查核心 AI 域名："

CORE_DOMAINS="
openai.com
chatgpt.com
api.openai.com
claude.ai
gemini.google.com
grok.com
copilot.microsoft.com
deepseek.com
perplexity.ai
"

MISSING=0

printf '%s\n' "$CORE_DOMAINS" |
while read -r DOMAIN
do
    [ -n "$DOMAIN" ] || continue

    if grep -Fxq "$DOMAIN" "$NORMALIZED"; then
        echo "  OK      $DOMAIN"
    else
        echo "  MISSING $DOMAIN"
        MISSING=1
    fi
done

# 上面的 while 在管道子 shell 中运行，
# 因此这里重新直接检查一次，确保状态可靠。

for DOMAIN in \
    openai.com \
    chatgpt.com \
    api.openai.com \
    claude.ai \
    gemini.google.com \
    grok.com \
    copilot.microsoft.com \
    deepseek.com \
    perplexity.ai
do
    if ! grep -Fxq "$DOMAIN" "$NORMALIZED"; then
        echo
        echo "错误：核心域名缺失：$DOMAIN"
        exit 1
    fi
done

echo
echo "核心域名检查通过"

# ========================================
# 7. 生成 AI.list
# ========================================

NEW_LIST="$TMP_DIR/AI.list"

{
    echo "# ========================================"
    echo "# AI Rules"
    echo "# Generated by hostzs/crossing"
    echo "# ========================================"
    echo "#"
    echo "# Sources:"
    echo "# - BlackMatrix7 OpenAI"
    echo "# - BlackMatrix7 Claude"
    echo "# - BlackMatrix7 Gemini"
    echo "# - BlackMatrix7 Copilot"
    echo "# - crossing custom.list"
    echo "#"
    echo "# ========================================"
    echo

    while read -r DOMAIN
    do
        echo "DOMAIN-SUFFIX,$DOMAIN"
    done < "$NORMALIZED"

} > "$NEW_LIST"

# ========================================
# 8. 生成 AI.yaml
# ========================================

NEW_YAML="$TMP_DIR/AI.yaml"

{
    echo "# ========================================"
    echo "# AI Rules"
    echo "# Generated by hostzs/crossing"
    echo "# ========================================"
    echo

    echo "payload:"

    while read -r DOMAIN
    do
        echo "  - DOMAIN-SUFFIX,$DOMAIN"
    done < "$NORMALIZED"

} > "$NEW_YAML"

# ========================================
# 9. 使用 Mihomo 生成 MRS
# ========================================

NEW_MRS="$TMP_DIR/AI.mrs"

if ! command -v mihomo >/dev/null 2>&1; then
    echo
    echo "错误：系统中没有 mihomo"
    exit 1
fi

echo
echo "使用 Mihomo 生成 AI.mrs"

mihomo convert-ruleset \
    domain \
    text \
    "$NEW_LIST" \
    "$NEW_MRS"

# ========================================
# 10. 检查 MRS
# ========================================

if [ ! -s "$NEW_MRS" ]; then
    echo "错误：AI.mrs 生成失败"
    exit 1
fi

MRS_SIZE="$(wc -c < "$NEW_MRS" | tr -d ' ')"

echo "AI.mrs 大小：${MRS_SIZE} bytes"

if [ "$MRS_SIZE" -lt 100 ]; then
    echo "错误：AI.mrs 文件异常"
    exit 1
fi

# ========================================
# 11. 检查是否真正发生变化
# ========================================

CHANGED=false

if [ ! -f "$OUTPUT_LIST" ] ||
   ! cmp -s "$NEW_LIST" "$OUTPUT_LIST"; then
    CHANGED=true
fi

if [ ! -f "$OUTPUT_YAML" ] ||
   ! cmp -s "$NEW_YAML" "$OUTPUT_YAML"; then
    CHANGED=true
fi

if [ ! -f "$OUTPUT_MRS" ] ||
   ! cmp -s "$NEW_MRS" "$OUTPUT_MRS"; then
    CHANGED=true
fi

# ========================================
# 12. 写入结果
# ========================================

if [ "$CHANGED" = "true" ]; then

    cp "$NEW_LIST" "$OUTPUT_LIST"
    cp "$NEW_YAML" "$OUTPUT_YAML"
    cp "$NEW_MRS" "$OUTPUT_MRS"

    echo
    echo "========================================"
    echo "AI 规则已更新"
    echo "========================================"

else

    echo
    echo "========================================"
    echo "AI 规则没有变化"
    echo "========================================"

fi

echo
echo "AI 域名数量：$COUNT"
echo "AI.list：$OUTPUT_LIST"
echo "AI.yaml：$OUTPUT_YAML"
echo "AI.mrs：$OUTPUT_MRS"
