name: Update Proxy Rules

on:
  workflow_dispatch:

  schedule:
    - cron: "0 18 * * *"

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Check source changes
        id: check
        run: |
          SOURCE="sources/manual-proxy.list"
          OUTPUT="output/proxy.yaml"

          CURRENT_HASH=$(sha256sum "$SOURCE" | awk '{print $1}')

          OLD_HASH=$(grep "^# SOURCE-SHA256:" "$OUTPUT" 2>/dev/null \
            | sed 's/^# SOURCE-SHA256: //' \
            || true)

          echo "当前 SHA256：$CURRENT_HASH"
          echo "旧 SHA256：$OLD_HASH"

          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "手动运行，强制生成"
            echo "changed=true" >> "$GITHUB_OUTPUT"

          elif [ "$CURRENT_HASH" != "$OLD_HASH" ]; then
            echo "manual-proxy.list 有变化"
            echo "changed=true" >> "$GITHUB_OUTPUT"

          else
            echo "manual-proxy.list 没有变化"
            echo "manual-proxy.list 没有变化"
            echo "changed=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Install latest stable Mihomo
        if: steps.check.outputs.changed == 'true'
        run: |
          set -e

          API="https://api.github.com/repos/MetaCubeX/mihomo/releases/latest"

          VERSION=$(curl -fsSL "$API" \
            | grep '"tag_name":' \
            | head -1 \
            | sed -E 's/.*"tag_name": "([^"]+)".*/\1/')

          echo "Mihomo 最新稳定版：$VERSION"

          if [ -z "$VERSION" ]; then
            echo "无法获取 Mihomo 最新版本"
            exit 1
          fi

          FILE="mihomo-linux-amd64-v1-${VERSION}.gz"
          URL="https://github.com/MetaCubeX/mihomo/releases/download/${VERSION}/${FILE}"

          echo "下载：$FILE"
          wget -q --show-progress "$URL"

          gunzip "$FILE"

          BINARY="${FILE%.gz}"

          chmod +x "$BINARY"
          sudo mv "$BINARY" /usr/local/bin/mihomo

          echo "安装完成："
          mihomo -v

      - name: Build proxy rules
        if: steps.check.outputs.changed == 'true'
        run: |
          chmod +x scripts/build.sh
          ./scripts/build.sh

      - name: Commit changes
        if: steps.check.outputs.changed == 'true'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add output/proxy.yaml output/proxy.list

          if git diff --cached --quiet; then
            echo "生成结果没有变化，不需要提交"
          else
            git commit -m "update proxy rules"
            git push
          fi
